# Generated by Django 4.2.1 on 2023-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='subcourse',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
