# Generated by Django 4.2.1 on 2023-05-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coursecategory_subcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcourse',
            name='coursecategory',
        ),
        migrations.AddField(
            model_name='gallary',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gallary',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
