# Generated by Django 4.2.1 on 2023-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
    ]
