# Generated by Django 4.2.1 on 2023-05-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='time',
        ),
    ]
