# Generated by Django 4.2.1 on 2023-05-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
