# Generated by Django 4.2.1 on 2023-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_slider_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('certificate', models.FileField(upload_to='media')),
                ('phone', models.IntegerField()),
                ('course', models.CharField(max_length=300)),
            ],
        ),
    ]
